FROM debian:buster
RUN apt-get update
RUN apt-get install -y \
    python3 \
    python3-dev \
    python3-pip \
    gcc \
    g++ \
    make
#veilator dependencies:
RUN apt-get install -y git autoconf g++ python3 flex bison make

WORKDIR /tmp
RUN git clone https://github.com/verilator/verilator verilator/
RUN cd verilator && autoconf && ./configure && make -j$(nproc) && make install

RUN pip3 install cocotb
