FROM debian:buster
RUN apt-get update
RUN apt-get install -y \
    python3 \
    python3-pip \
    git

WORKDIR /tmp
RUN git clone https://github.com/olofk/edalize.git edalize/
RUN cd edalize && python3 -m pip install -e .

