FROM debian:bullseye
RUN apt-get update
RUN apt-get install -y \
    build-essential \
    clang cmake \
    git python3 python3-dev \
    libboost-all-dev libeigen3-dev

WORKDIR /tmp
RUN git clone --recursive https://github.com/YosysHQ/prjtrellis
RUN cd prjtrellis/libtrellis && cmake -DCMAKE_INSTALL_PREFIX=/usr/local . && make -j $(nproc) && make install && cd ../..
RUN git clone --recursive https://github.com/YosysHQ/nextpnr.git 
RUN cd nextpnr && cmake . -DARCH=ecp5 -DTRELLIS_INSTALL_PREFIX=/usr/local && make -j $(nproc) && make install && cd ..


