FROM debian:buster
RUN apt-get update \
    && apt-get install -y apt-transport-https dirmngr \ 
           build-essential wget libssl-dev apt-transport-https ca-certificates curl gnupg2 software-properties-common \
    && curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add - \
    && add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" \	
    && curl -sL https://deb.nodesource.com/setup_10.x | bash - \
    && apt-get update \
    && apt-get install -y docker-ce docker-ce-cli 

