FROM debian:buster
RUN apt-get update
RUN apt-get install -y \
    build-essential \
    clang \
    bison \
    flex \
    libreadline-dev \
    gawk \
    tcl-dev \
    libffi-dev \
    git \
    graphviz \
    xdot \
    pkg-config \
    python3 \
    libboost-system-dev \
    libboost-python-dev \
    libboost-filesystem-dev \
    zlib1g-dev

WORKDIR /tmp
RUN git clone https://github.com/YosysHQ/yosys.git yosys/
RUN cd yosys && make -j$(nproc) config-gcc && make -j$(nproc) install

