FROM debian:bullseye
RUN apt-get update
RUN apt-get install -y git autoconf g++ python3 flex bison make

WORKDIR /tmp
RUN git clone https://github.com/verilator/verilator verilator/
RUN cd verilator && autoconf && ./configure && make -j$(nproc) && make install
