FROM debian:buster
RUN apt-get update
RUN apt-get install -y \
    python3 \
    python3-setuptools \
    python3-pip \
    git

RUN pip3 install git+https://github.com/lowRISC/fusesoc.git@ot
RUN pip3 install git+https://github.com/antmicro/edalize.git@surelog
